type: "transformation"
version: "1.0"
pipeline:
  components:
    M_STUDENT:
      type: "table-input"
      parameters:
        componentName: "M_STUDENT"
        database: "${env_database}"
        schema: "${env_schema}"
        targetTable: "M_STUDENT"
        columnNames:
        - "ID"
        - "NAME"
        - "AGE"
        - "CITY"
        timeOffset: ""
    Rename (ID->Rename_ID,Name->Rename->Rename_Name..):
      type: "rename"
      sources:
      - "M_STUDENT"
      parameters:
        componentName: "Rename (ID->Rename_ID,Name->Rename->Rename_Name..)"
        columnMapping:
        - - "ID"
          - "Rename_ID"
        - - "NAME"
          - "Rename_Name"
        - - "AGE"
          - "Rename_Age"
        - - "CITY"
          - "Rename_City"
        includeInputColumns: "No"
    Rewrite Table:
      type: "rewrite-table"
      sources:
      - "Rename (ID->Rename_ID,Name->Rename->Rename_Name..)"
      parameters:
        componentName: "Rewrite Table"
        warehouse: "[Environment Default]"
        database: "${env_database}"
        schema: "${env_schema}"
        targetTable: "DPC_MTLN_TEST_1"
        orderBy:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
  variables:
    env_schema:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "DBT_MKHAMBADKAR"
    env_database:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "INTERNAL_TRAINING"
design:
  components:
    M_STUDENT:
      position:
        x: 300
        "y": 50
      tempMetlId: 1184069
    Rename (ID->Rename_ID,Name->Rename->Rename_Name..):
      position:
        x: 540
        "y": 70
      tempMetlId: 1184072
    Rewrite Table:
      position:
        x: 750
        "y": 50
      tempMetlId: 1184073
