type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "SQL Script"
        - "SQL Script 2"
        - "SQL Script 3"
        - "SQL Script 4"
      parameters:
        componentName: "Start"
    SQL Script:
      type: "sql-executor"
      skipped: true
      parameters:
        componentName: "SQL Script"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: "select * from INTERNAL_TRAINING.DBT_MKHAMBADKAR.DPC_MTLN_TEST_1;"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    SQL Script 2:
      type: "sql-executor"
      parameters:
        componentName: "SQL Script 2"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: "select * from ${INTERNAL_TRAINING}.DBT_MKHAMBADKAR.DPC_MTLN_TEST_1;"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    SQL Script 3:
      type: "sql-executor"
      skipped: true
      parameters:
        componentName: "SQL Script 3"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: "select * from INTERNAL_TRAINING.${DBT_MKHAMBADKAR}.DPC_MTLN_TEST_1;"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    SQL Script 4:
      type: "sql-executor"
      parameters:
        componentName: "SQL Script 4"
        scriptLocation: "Component"
        declareSqlVariables: "Include selected"
        variablesToInclude:
        sqlScript: "select * from ${INTERNAL_TRAINING}.${DBT_MKHAMBADKAR}.DPC_MTLN_TEST_1;"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    Start:
      position:
        x: -230
        "y": -90
      tempMetlId: 1
    SQL Script:
      position:
        x: -30
        "y": -190
      tempMetlId: 7
    SQL Script 2:
      position:
        x: -30
        "y": -80
      tempMetlId: 8
    SQL Script 3:
      position:
        x: -30
        "y": 30
      tempMetlId: 9
    SQL Script 4:
      position:
        x: -80
        "y": 140
      tempMetlId: 10
